# version: "3.9"

# services:
#   api:
#     container_name: payu_api
#     build: .
#     ports:
#       - "8000:8000"
#     restart: always

version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"

    volumes:
      - ./src:/app   # sync local src → container

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload